### PR TITLE
Bump to Java 8, Jenkins 2.60.3 and related dependencies

### PR DESCRIPTION
**Pull request by alexsomai**

### CODE REVIEW

**Comment by alexsomai** [comment]
It seems that I have some backwards compatibility issues, therefore some tests are failing after the upgrade. 

I think that if I solve one test, the other will follow. But the question is, should I fix something in the tests, or in the code base? 🤔 

Take for example this test `DisplayNameRunFilterTest#testDisplayName`: https://github.com/jenkinsci/run-selector-plugin/blob/c4205f57d10c9d6845c851d8cd43a77a8b45dd24/src/test/java/org/jenkinsci/plugins/runselector/filters/DisplayNameRunFilterTest.java#L50

When I create a new build, I create a new `ParameterAction`, like:
```
new ParametersAction(
    new StringParameterValue("NUM", "RC1")
)
```

And the issue is that this parameter is not assigned as `envVar` in `RunSelectorContext#constructEnvVars`: https://github.com/jenkinsci/run-selector-plugin/blob/c4205f57d10c9d6845c851d8cd43a77a8b45dd24/src/main/java/org/jenkinsci/plugins/runselector/context/RunSelectorContext.java#L356

Any hints how to solve this issue is appreciated 🙂.

**Comment by daniel-beck** [comment]
Add a `ParametersDefinitionProperty` to the job first. See https://jenkins.io/security/advisory/2016-05-11/

(3.5 years ago!)

**Comment by alexsomai** [comment]
That solved the issues. Thank you, Daniel!

@jenkinsci/code-reviewers could you guys please review this?

**Comment by alexsomai** [comment]
Hey guys, I would just need a second opinion before I could merge this. @martinda @oleg-nenashev @daniel-beck. Thanks :)

**Comment by martinda** [comment]
Looks like a good step forward, but I am not an authority here, anyway +1 from me.

**Review by oleg-nenashev — APPROVED** [review]
I missed it somehow. LGTM, thanks!

**Pull request merged**
