### PR TITLE
Prepare for beta release

### PR DESCRIPTION
**Pull request by alexsomai**
I'd like to perform a beta release of this plugin.
I'll test it the best I can and according to my knowledge, and if everything goes well, maybe in a week or so, we can perform a stable release.

CC @ikedam @oleg-nenashev @martinda

### CODE REVIEW

**Comment by alexsomai** [comment]
There is one more thing that bugs me: the `pom.xml` file has a lot of test dependencies which are not required (maybe because I've commented out most of the tests).
My suggestion is to remove the test dependencies that are not required, and add them along the way, as needed.

**Comment by oleg-nenashev** [comment]
+1 for removing the dependencies.
Just to make sure, have you uncommented the related tests in this plugin.

Do you also need a PR builder before the release? If yes, please create an INFRA ticket to me

**Comment by alexsomai** [comment]
Unfortunately I didn't have that much time to take care of the tests. Most of the tests are still commented. In order to uncomment them, they still need a few adjustments.
I'll try to allocate some time this week, before the actual release, for having some tests working.

Yes, I think that CI would be useful, I'll create the ticket.

**Comment by oleg-nenashev** [comment]
Triggering the build for https://issues.jenkins-ci.org/browse/INFRA-878

**Comment by ikedam** [comment]
Looks good to me.
+1 for removing test dependencies. Though, I think you can leave it for the beta release if it causes failures (e.g. compilation errors for imports) and consume your time to fix them.

**Pull request merged**
