### PR TITLE
[JENKINS-36501] Rename packages and classes to match RunSelector

### PR DESCRIPTION
**Pull request by alexsomai**
Related to issue [[JENKINS-36501]](https://issues.jenkins-ci.org/browse/JENKINS-36501)

Summary of this pull request:
- rename the root package to _org.jenkinsci.plugins.runselector_
- rename the _BuildSelector_ to _RunSelector_ (as well as all of its implementations and parameter names)
- rename the _BuildFilter_ to _RunFilter_ (as well as all of its implementations and parameter names)
- move all _RunSelector_ implementations under _org.jenkinsci.plugins.runselector.selectors_ package
- move all _RunFIlter_ implementations under _org.jenkinsci.plugins.runselector.filters_ package
- rename _CopyArtifact...Context_ to _RunSelector...Context_

The changes may be a bit difficult to track, since there are a lot of modified files, but I've tried to summarize what I did.

CC @ikedam @oleg-nenashev @martinda

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
Seems something went wrong with files. Encoding? I would not expect full diffs

**Comment by alexsomai** [comment]
I don't know why GitHub is showing the diffs like this. For example if I look at the changes in IntelliJ, the diffs are shown only on renaming.

**Comment by ikedam** [comment]
Looks good to me.
I like this new structure.

I suppose you changed line feeds (CRLF to LF) for files with full diffs.
It depends on the configuration of your IDE, and I think it's OK to change to LF on this occasion as CRLF often cause problems when you maintain the plugin.

You can see diffs without changes of line feeds with:
https://github.com/jenkinsci/run-selector-plugin/pull/3/files?w=1

**Comment by ikedam** [comment]
Some files looks still remain as copyartifact:
https://github.com/alexsomai/run-selector-plugin/tree/rename-packages-classes/src/main/resources/hudson/plugins/copyartifact

**Comment by oleg-nenashev** [comment]
> It depends on the configuration of your IDE, and I think it's OK to change to LF on this occasion as CRLF often cause problems when you maintain the plugin.

+1 It's fine to reformat it (just difficult to review if there are any real changes)

**Comment by oleg-nenashev** [comment]
Maybe makes sense to keep extension points on the top level, but it's just IMHO. The current approach looks good to me as well

**Comment by oleg-nenashev** [comment]
@alexsomai @ikedam 
A kind of ideological question. Is the "Run Selector Plugin" name correct since there is also RunFilter extension point. IMHO it's bot a big problem, but maybe artifact ID could be generalized a bit. NIT

**Comment by alexsomai** [comment]
I agree to have the extension points `RunSelector` and `RunFilter` as top level. I've just noticed that `RunFilter` does not implement `ExtensionPoint`. I think it should, right?

From my understanding, the `RunFilter` is also some sort of selector. Based on it, you can specify additional search criteria for selecting your build (run).

**Comment by oleg-nenashev** [comment]
> From my understanding, the RunFilter is also some sort of selector. Based on it, you can specify additional search criteria for selecting your build (run).

Up to you. Maybe it's possible to merge them somehow or to decouple to separate extension points

**Comment by ikedam** [comment]
`RunFilter` is used as an additional condition for `RunSelector` as alexsomai pointed, and "Run Selector Plugin" looks correct to me.
I considered to rename `RunSelector` to `RunEnumerator` when started to develop copyartifact 2.0, but I didn't do that as `enumerator` is long and sounds too technical.

**Comment by ikedam** [comment]
> I've just noticed that RunFilter does not implement ExtensionPoint. I think it should, right?

Yes, I missed that.
As far as I know, `ExtensionPoint` is used to list classes in [wiki](https://wiki.jenkins-ci.org/display/JENKINS/Extension+points).

**Comment by alexsomai** [comment]
@ikedam @oleg-nenashev WDYT about this PR? I am thinking to merge it too.
As I said, there will be at least one more PR with minor changes and refactoring.

**Comment by ikedam** [comment]
Looks good to me.

**Comment by alexsomai** [comment]
This PR should be merged into _master_. The PR was created against another branch for a better changes view.
Closing in favor of #4.

**Pull request closed without merging**
