### PR TITLE
[JENKINS-36484] Remove deprecated code

### PR DESCRIPTION
**Pull request by alexsomai**
Related to issue [[JENKINS-36484]](https://issues.jenkins-ci.org/browse/JENKINS-36484)

Summary of this pull request:
- Removed the deprecated code and features that were inherited from the Copy Artifact plugin

Hopefully I didn't remove to much code. At this point it may be a bit difficult for me to figure out what is needed and what not.

CC @ikedam @oleg-nenashev @martinda

### CODE REVIEW

**Comment by ikedam** [comment]
Though I haven't review all changes yet, -1 for removing test codes.
I know it's a really hard work to migrate test codes, but I want tests for selecting runs same in copyartifact-plugin.
I don't want that from the first release, and how about only disabling tests (e.g. renaming the test directory) for now?
I want to know how you plan about tests.

**Comment by alexsomai** [comment]
The current tests were mainly based on the CopyArtifact classes, which I have removed. So simply disabling the tests (mark them with @\Ignore) wouldn't have been an option, because I would get compile errors. For this PR, I can simply add some empty test classes.
I will definitely create tests. I was thinking to have tests for each selector, e.g. StatusBuildSelectorTest, SpecificBuildSelectorTest, etc.

**Comment by alexsomai** [comment]
I have also removed some backward compatibility code. I don't know exactly what impact this will have on CopyArtifact v2 migration.

**Comment by oleg-nenashev** [comment]
@alexsomai 
I agree with @ikedam that tests would be useful. 
At least direct tests like [SpecificBuildSelectorTest](https://github.com/jenkinsci/copyartifact-plugin/blob/master/src/test/java/hudson/plugins/copyartifact/SpecificBuildSelectorTest.java) could be retained. These tests actually do not depend on core CopyArtifact functionality, so their migration should be possible.

**Comment by ikedam** [comment]
`CopyArtifactTest` also includes tests for some selectors and is useful as a TODO list to writing tests in future.
I agree it's not reasonable to waste time to have tests pass compilation now, and we can put those files away from the src directory.
I worry that we can no longer  track histories of tests if once they are removed.
When adding tests, we can put a test class back to to the src directory and fix it, or write a brand new test class and say "tests in this old class is replaced with tests in this new class" in a pull request. That ensures all features in copyartifact1.x works in run-selector.

> I have also removed some backward compatibility code. I don't know exactly what impact this will have on CopyArtifact v2 migration.

Don't mind about compatibility codes.
I plan to introduce internediate classes for migration to copyartifact.
That makes other plugins designed for copyartifact 1.x work even after renaming packages, classes in run-selector.

**Comment by alexsomai** [comment]
I've reverted the changes made on tests and put them back. I've commented the code where it was not compiling. The rest of tests I've marked them with Ignore, since most of them are failing.
I did a force push this time.

**Comment by ikedam** [comment]
I finished reviewing.
- You can also remove followings:
  - `BuildFilter#isSelectable`
- Following help files are still useful. (You may want to move them to `webapp` to use from multiple jelly files)
  - `src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-buildFilter.html`
  - `src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-selector.html`
  - `src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-verbose.html`
- Notes (no need to handle in this request, and may help other pull requests)
  - You have to have `BuildSelectorParameter.initAliases` called.
    - It is no longer called as `CopyArtifactPlugin` is removed.
    - You can use [`InitMilestone`](http://javadoc.jenkins-ci.org/hudson/init/InitMilestone.html) instead.
  - `ParameterizedBuildSelector` supports variable names (not variable expressions!). It can be deprecated and removed.
  - You can merge `CopyArtifactCommonContext` into `CopyArtifactPickContext`
    - As `CopyArtifactOperationContext` no longer exists.
  - You can now assume that all descriptors of `BuildSelector` is derived from `BuildSelectorDescriptor`.
    - You can remove notes in `BuildSelectorDescriptor` ("Be aware that BuildSelector in the old scheme might not use this.")

**Comment by alexsomai** [comment]
@ikedam thank you for your time reviewing this.
I am planning to create a new PR with some additional refactoring. That PR will also include the changes that you have suggested. I think that they will be easier to track in this way.

I think that this one can be merged for now.

**Comment by ikedam** [comment]
Looks good to me.

**Pull request merged**
