### PR TITLE
Use uppercase names for build status 

### PR DESCRIPTION
**Pull request by alexsomai**
One of the changes that @jglick suggested on this thread https://groups.google.com/forum/#!topic/jenkinsci-dev/IZ2EZR6tjXo was to use de-camel cased names: `successful` instead of `Successful`. 
So that the Pipeline syntax would be:

``` groovy
def runWrapper = runSelector job: 'upstream-project-name', 
  selector: [$class: 'StatusRunSelector', buildStatus: 'successful'] 
```

This means that I have to change the enum names, so the code base looks like in this PR.
Personally I don't like that much having enums with de-camel cased names.

What if I change the syntax to upper case? To have `SUCCESSFUL` (personally I'd prefer this one).
e.g. 

``` groovy
def runWrapper = runSelector job: 'upstream-project-name', 
  selector: [$class: 'StatusRunSelector', buildStatus: 'SUCCESSFUL']
```

Opinions @jglick @ikedam @oleg-nenashev @martinda?

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
I'd also prefer uppercase. It's good for constants

**Comment by martinda** [comment]
+1 for uppercase.

**Comment by ikedam** [comment]
+1 for uppercases as enum values.

It sounds too strange to use lower cases for enum values to me, and I don't think @jglick proposed to use lower cases for enum values.
I suppose he didn't know it's implemented with enum,
or he might have proposed to  introduce a new constructor `StatusRunSelector(String)`
or he might have proposed to use lower cases for values of `Symbol`.

Anyway, I'm not sure what he exactly meant with "APIs like lastSuccessfulBuild"
(a value of Symbol? property name used with groovy? permalink name?)

**Comment by oleg-nenashev** [comment]
@alexsomai, so have you decided not to use uppercase?

**Comment by alexsomai** [comment]
@oleg-nenashev I am using uppercase, see 9f88246

**Comment by oleg-nenashev** [comment]
Seems I was reviewing the previous version. 👍

**Comment by ikedam** [comment]
Looks good to me.

**Pull request merged**
