### PR TITLE
Rename Pipeline step to 'selectRun'

### PR DESCRIPTION
**Pull request by alexsomai**
Rename Pipeline step to `selectRun` based on the discussions: https://groups.google.com/forum/#!topic/jenkinsci-dev/IZ2EZR6tjXo

CC @ikedam @oleg-nenashev @martinda

### CODE REVIEW

**Comment by alexsomai** [comment]
@ikedam don't worry about #10, I'll make the tests adjustments after it's merged.

**Comment by oleg-nenashev** [comment]
Seems README needs to be updated as well.
👍 for the code

**Comment by martinda** [comment]
As a non-IDE person, I use grep -R to see if I missed anything when doing a change like this. In any case +1

**Comment by ikedam** [comment]
Looks good to me.

> don't worry about #10, I'll make the tests adjustments after it's merged.

Thanks!

**Pull request merged**
